USE [master]
GO
/****** Object:  Database [nb.linux-tree]    Script Date: 1/6/2019 11:16:08 AM ******/
CREATE DATABASE [nb.linux-tree]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'linux-tree', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\linux-tree.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'linux-tree_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\linux-tree_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [nb.linux-tree] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [nb.linux-tree].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [nb.linux-tree] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [nb.linux-tree] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [nb.linux-tree] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [nb.linux-tree] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [nb.linux-tree] SET ARITHABORT OFF 
GO
ALTER DATABASE [nb.linux-tree] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [nb.linux-tree] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [nb.linux-tree] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [nb.linux-tree] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [nb.linux-tree] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [nb.linux-tree] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [nb.linux-tree] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [nb.linux-tree] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [nb.linux-tree] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [nb.linux-tree] SET  DISABLE_BROKER 
GO
ALTER DATABASE [nb.linux-tree] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [nb.linux-tree] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [nb.linux-tree] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [nb.linux-tree] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [nb.linux-tree] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [nb.linux-tree] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [nb.linux-tree] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [nb.linux-tree] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [nb.linux-tree] SET  MULTI_USER 
GO
ALTER DATABASE [nb.linux-tree] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [nb.linux-tree] SET DB_CHAINING OFF 
GO
ALTER DATABASE [nb.linux-tree] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [nb.linux-tree] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [nb.linux-tree] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [nb.linux-tree] SET QUERY_STORE = OFF
GO
USE [nb.linux-tree]
GO
/****** Object:  Table [dbo].[Distro]    Script Date: 1/6/2019 11:16:08 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Distro](
	[Id] [int] NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Website] [varchar](250) NOT NULL,
	[Article] [text] NULL,
 CONSTRAINT [PK_Distro] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DistroRelationship]    Script Date: 1/6/2019 11:16:08 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DistroRelationship](
	[Id] [int] NOT NULL,
	[DistroId] [int] NOT NULL,
	[ParentDistroId] [int] NOT NULL,
 CONSTRAINT [PK_DistroRelationship] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DistroVersion]    Script Date: 1/6/2019 11:16:08 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DistroVersion](
	[Id] [int] NOT NULL,
	[Version] [varchar](20) NOT NULL,
	[Order] [int] NOT NULL,
	[Article] [text] NULL,
	[DistroId] [int] NOT NULL,
	[VersionDate] [date] NOT NULL,
 CONSTRAINT [PK_DistroVersion] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[DistroRelationship]  WITH CHECK ADD  CONSTRAINT [FK_DistroRelationship_Distro] FOREIGN KEY([DistroId])
REFERENCES [dbo].[Distro] ([Id])
GO
ALTER TABLE [dbo].[DistroRelationship] CHECK CONSTRAINT [FK_DistroRelationship_Distro]
GO
ALTER TABLE [dbo].[DistroVersion]  WITH CHECK ADD  CONSTRAINT [FK_DistroVersion_Distro] FOREIGN KEY([DistroId])
REFERENCES [dbo].[Distro] ([Id])
GO
ALTER TABLE [dbo].[DistroVersion] CHECK CONSTRAINT [FK_DistroVersion_Distro]
GO
USE [master]
GO
ALTER DATABASE [nb.linux-tree] SET  READ_WRITE 
GO
